version: "3.8"

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    entrypoint: ["python", "/usr/src/utk-backend/server.py"] 
    volumes:
      - "./services/backend:/usr/src/utk-backend"
      - "./data:/usr/src/utk-backend/data"
    ports:
      - 5004:5000
    environment:
      - FLASK_ENV=development

  jupyterapi:
    build:
      context: ./services/jupyterAPI
      dockerfile: Dockerfile
    volumes:
      - "./services/jupyterAPI:/usr/src/utk-jupyterAPI"
      - "./data:/usr/src/utk-jupyterAPI/data"
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=docker 